chore(Java): handle deserialization scenario that currently throws an IndexOutOfBoundsException (#2399)
This test fails. I had expected it to fail with null when wrong type was
used (because of #2392 but this fails differently from that - the use
case where I saw a null returned was a Scala use case)

Fails with IndexOutOfBoundsException while I would expect a nicer
exception. Maybe should be a Fory DeserializationException.
```
java.lang.IndexOutOfBoundsException: readerIndex(1) + length(2) exceeds size(7): org.apache.fory.memory.MemoryBuffer$BoundChecker@4e268090

	at org.apache.fory.memory.MemoryBuffer$BoundChecker.fillBuffer(MemoryBuffer.java:186)
	at org.apache.fory.memory.MemoryBuffer.checkReadableBytes(MemoryBuffer.java:2440)
	at org.apache.fory.ForyTest_Struct2ForyCodec_0.read(ForyTest_Struct2ForyCodec_0.java:59)
	at org.apache.fory.Fory.readDataInternal(Fory.java:1055)
	at org.apache.fory.Fory.deserializeJavaObject(Fory.java:1223)
	at org.apache.fory.Fory.deserializeJavaObject(Fory.java:1200)
	at org.apache.fory.ForyTest.testDeserializeJavaObjectWrongType(ForyTest.java:689)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```